# Generated by Django 5.0.4 on 2024-11-12 05:09

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, validators=[backend.models.validate_Name])),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('Phone_no', models.IntegerField(validators=[backend.models.validate_Phone_no])),
            ],
        ),
    ]
