# Generated by Django 5.0.4 on 2024-11-12 05:16

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Phone_no',
            field=models.BigIntegerField(validators=[backend.models.validate_Phone_no]),
        ),
    ]
