# Generated by Django 5.0.4 on 2024-11-12 06:08

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_registration_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Phone_no',
            field=models.CharField(max_length=10, validators=[backend.models.validate_Phone_no]),
        ),
    ]
